### ISSUE TITLE
What would be a suitable section to list Coder module registry.

### ISSUE THREAD

**Issue by matifali** [shuaibiyy/awesome-tf#251]
I want to list https://registry.coder.com/modules but needed help deciding what section would be a suitable choice to list it under. 

The Coder Registry is a collection of [Templates](https://registry.coder.com/templates) and [Modules](https://registry.coder.com/modules) used to create and extend Coder workspaces.

**Comment by antonbabenko** [comment]
I think it is too specific to the product (Coder) and it is not best to be in this repository.
